import Notification from "@/components/notification/Notification";
import "./styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/menu/Navbar";
import Footer from "@/components/Footer";
import { faFacebook, faInstagram } from "@fortawesome/free-brands-svg-icons";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const footerData = {
    cityAddresses: [
      {
        id: "2",
        city: "Canada",
        address: "826 Brimorton DriveScarborough",
        phoneNo: "+1 647-773-8546",
        pinCode: "ON M1G 2S9",
        state: "Toronto",
      },
      {
        id: "1",
        city: "India",
        phoneNo: "",
        address: "Plot No. 4, Mahavir Park, Baner",
        pinCode: "Pune – 411045",
        state: "Maharashtra",
      },
    ],

    emailId: "manas@incerro.ai",
    copyrightText:
      "Copyright © 2023 Invasion Software Technologies Pvt Ltd. All rights reserved.",
    socialMediaLinks: [
      {
        id: "1",
        url: "https://facebook.com/incerro",
        name: "facebook",
      },
      {
        id: "3",
        url: "https://www.instagram.com/incerro.ai",
        name: "instagram",
      },
      {
        id: "2",
        url: "https://www.linkedin.com/company/incerro",
        name: "linkedin",
      },
      {
        id: "4",
        url: "mailto:manas@incerro.ai",
        name: "email",
      },
    ],
  };
  return (
    <html lang="en">
      <body className={inter.className}>
        <Notification />
        <Navbar />
        {children}
        <Footer
          cityAddresses={footerData.cityAddresses}
          emailId={footerData.emailId}
          socialMediaLinks={footerData.socialMediaLinks}
          copyrightText={footerData.copyrightText}
        />
      </body>
    </html>
  );
}
